# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RealTimeParkingBookingSystem' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for RealTimeParkingBookingSystem
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'MBProgressHUD', '~> 1.0'
    pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :branch => 'master'
    pod 'RxSwift', '~> 3.1'
    pod 'IQKeyboardManagerSwift'
    pod 'ObjectMapper', '~> 2.2'
    pod 'SwiftMoment'
    
    target 'RealTimeParkingBookingSystemTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'RealTimeParkingBookingSystemUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
